#!/bin/bash

# Do not edit this file!

# To change authToken and owner id: 
## edit your Config Vars in heroku/app/settings and 
## restart the bot by turning the worker off and back on

echo "Creating requirements-cli.txt..."
cd /home/wiguna-cermin
cat > requirements-cli.txt << EOF
{ 
oauth2client
google-api-python-client
progress
progressbar2
httplib2shim
google_auth_oauthlib
pyrogram
}
EOF
echo "Done."

echo "Starting Bot..."
python3 -m bot
