#!/bin/bash

# Do not edit this file!

# To change authToken and owner id: 
## edit your Config Vars in heroku/app/settings and 
## restart the bot by turning the worker off and back on

echo "Creating requirements.txt..."
cd /home/Nyaa-Telegram-Bot
cat > requirements.txt << EOF
{
pyrogram
aiohttp
TgCrypto
}
EOF
echo "Done."

echo "Starting Bot..."
python3 -m bot
